In [ ]:
import numpy as np

In [37]:
z = np.zeros(10)
print(z)
z = np.ones(10)
print(z)
z = np.full(10, 2.5)
print(z)
z = np.arange(10, 50)
print(z)
z = z[::-1]
print(z)
z = np.arange(9).reshape(3, 3)
print(z)
nz = np.nonzero([1,5,0,10,4,0])#index nonzero elements
print(nz)
z = np.eye(3)
print(z)
z = np.random.random((3, 3, 3))
print(z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 3, 4]),)
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[[ 0.72140072  0.58429731  0.67169058]
  [ 0.67601571  0.6190195   0.03638763]
  [ 0.79291491  0.99085196  0.08999026]]

 [[ 0.07719927  0.10577005  0.77638855]
  [ 0.24098335  0.64431651  0.30174239]
  [ 0.64090931  0.83829419  0.60209124]]

 [[ 0.403725    0.73660979  0.8242303 ]
  [ 0.42178119  0.25841494  0.86182826]
  [ 0.43250111  0.7796254   0.06524571]]]


In [40]:
z = np.random.random((10, 10))
zmin, zmax = z.min(), z.max()
print(z)
print(zmin, zmax)

[[ 0.16726544  0.66171444  0.93637966  0.71564862  0.10230165  0.00833739
   0.24947349  0.43334084  0.6462008   0.97245748]
 [ 0.11031156  0.33168265  0.879941    0.73370123  0.15402893  0.93140373
   0.98147265  0.87997204  0.18700207  0.35038247]
 [ 0.47625706  0.51989117  0.68817047  0.14585105  0.52690485  0.77256095
   0.28700435  0.60893808  0.41066776  0.96520925]
 [ 0.50533288  0.15597277  0.44650987  0.05820554  0.60037419  0.52964455
   0.94164375  0.80227621  0.03388099  0.36341504]
 [ 0.76105051  0.08997782  0.03193115  0.0100715   0.87156154  0.11757781
   0.83321648  0.86108815  0.18948502  0.69329718]
 [ 0.35272497  0.9244566   0.24745715  0.44914713  0.57839969  0.76060898
   0.14462632  0.86121875  0.82551579  0.67467119]
 [ 0.07349061  0.77381317  0.29687063  0.51653476  0.1167562   0.14806589
   0.67509862  0.14758815  0.98917457  0.68890259]
 [ 0.7591443   0.22761914  0.02724843  0.05171405  0.95697785  0.94568219
   0.99547216  0.02520726  0.83634603  0.37075814]


In [42]:
z = np.random.random(30)
print(z)
print(z.mean())

[ 0.79591958  0.06810567  0.28624555  0.73781516  0.13358701  0.35808874
  0.58625972  0.56909246  0.97007368  0.7591172   0.3257169   0.84601949
  0.94435215  0.50493794  0.81994293  0.04453086  0.66993583  0.84687091
  0.06204717  0.39454982  0.08689098  0.77598559  0.25253903  0.53239761
  0.63508183  0.00849765  0.67379384  0.80048596  0.87572002  0.96900855]
0.544453661203


In [45]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [61]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
0.3 == 0.1 * 3)

nan False False nan False


In [72]:
z = np.diag(np.arange(1, 5))
print(z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [73]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [78]:
Z = np.dot(np.ones((7,4)), np.ones((4,3)))
print(Z)

[[ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]]


In [79]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [87]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [92]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
35.09521434322718
35


In [99]:
import sys, pygame
w = pygame.display.flip()

ModuleNotFoundError: No module named 'pygame'

In [124]:
from IPython.display import Image
from IPython import display

In [131]:
a = 5
display.display(5 - 2)

3